### ISSUE TITLE
Error loading syntax file "Packages/Nunjucks Syntax/Nunjucks.tmLanguage"

### ISSUE THREAD

**Issue by manV** [robmoggach/sublime-nunjucks#1]
Hey I recently installed this package on sublime text 2 and when I select nunjucks syntex from view>syntex it's giving me following error and text grays out.

Error loading syntax file "Packages/Nunjucks Syntax/Nunjucks.tmLanguage": boost::bad_any_cast: failed conversion using boost::any_cast

**Comment by alrayyes** [comment]
Same issue with ST2

**Comment by rludgero** [comment]
@Sesshoumaru404 solution works, thx.

**Comment by kruncher** [comment]
Same issue for me; installing this package via the package manager simply doesn't work anymore. The "Nunjucks" menu item does not appear. However the andres-risso fork that @Sesshoumaru404 kindly pointed out does work properly.

**Comment by rjmoggach** [comment]
I haven't used nunjucks in ages. If someone wants to take this off my hands I'll happily transfer-
