### ISSUE TITLE
How do you manually install this? 

### ISSUE THREAD

**Issue by juanfernandes** [robmoggach/sublime-nunjucks#16]
This package is still not showing in PackageControl. 

Is there a way I can add it manually? I know its not ideal, but I don't want to have to switch editors just because of this. 

Thanks in advance.

**Comment by imjared** [comment]
check out: https://github.com/mogga/sublime-nunjucks/issues/1#issuecomment-46787540

**Comment by juanfernandes** [comment]
Thanks @imjared
